// revisionRequestsData.js

export const revisionRequestsData = [
  {
    id: 1,
    name: "Feeler Gauge",
    idNo: "KTRC-EQ-0089",
    serialNo: "1412167306",
    customerName: "KAILTECH TEST & RESEARCH CENTRE PVT. LTD.",
    inwardEntryNo: "3437",
    certificateNo: "KTRC/2504R000201",
    status: "1",
    actions: "aa",
    revNo: "aa",
    reason: "04/10/2025",
    remark: "Er. Ruby S. Malhotra",
    requestedOn: "04/10/2025",
    requestedBy: "Er. Ruby S. Malhotra",
    approvedOn: "Completed",
    approvedBy: "",
  },
  {
    id: 2,
    name: "Digital Clamp Meter",
    idNo: "KTRC-EQ-0051",
    serialNo: "1206183",
    customerName: "KAILTECH TEST & RESEARCH CENTRE PVT. LTD.",
    inwardEntryNo: "3437",
    certificateNo: "KTRC/2504R001701",
    status: "1",
    actions: "my name is moin",
    revNo: "eeds",
    reason: "24/09/2025",
    remark: "Er. Ruby S. Malhotra",
    requestedOn: "24/09/2025",
    requestedBy: "Er. Ruby S. Malhotra",
    approvedOn: "Completed",
    approvedBy: "",
  },
  {
    id: 3,
    name: "Digital Thermometer",
    idNo: "KTRC-MS-0084",
    serialNo: "NA",
    customerName: "KAILTECH TEST & RESEARCH CENTRE PVT. LTD.",
    inwardEntryNo: "3437",
    certificateNo: "KTRC/2504R000101",
    status: "1",
    actions: "Engine problem",
    revNo: "my name is moin",
    reason: "19/08/2025",
    remark: "Er. Ruby S. Malhotra",
    requestedOn: "19/08/2025",
    requestedBy: "Er. Ruby S. Malhotra",
    approvedOn: "Completed",
    approvedBy: "",
  },
  {
    id: 4,
    name: "Steel Scale",
    idNo: "KTRC-EQ-0272",
    serialNo: "N.A",
    customerName: "KAILTECH TEST & RESEARCH CENTRE PVT. LTD.",
    inwardEntryNo: "3437",
    certificateNo: "KTRC/2504R000701",
    status: "1",
    actions: "my name is moin",
    revNo: "i am from shajapur",
    reason: "19/08/2025",
    remark: "Er. Ruby S. Malhotra",
    requestedOn: "19/08/2025",
    requestedBy: "Er. Ruby S. Malhotra",
    approvedOn: "Completed",
    approvedBy: "",
  },
  {
    id: 5,
    name: "Weight Box",
    idNo: "INST 924",
    serialNo: "NA",
    customerName: "SUN PHARMACEUTICAL INDUSTRIES LIMITED",
    inwardEntryNo: "3183",
    certificateNo: "KTRC/2412R002328",
    status: "1",
    actions: "To add Remark For Second Weight Identification",
    revNo: "To add Remark For Second Weight Identification",
    reason: "16/05/2025",
    remark: "Pooja Agrawal",
    requestedOn: "17/05/2025",
    requestedBy: "Pooja Agrawal",
    approvedOn: "Completed",
    approvedBy: "",
  },
];
