// Import Dependencies
import { createColumnHelper } from "@tanstack/react-table";

// Local Imports
import { RowActions } from "./RowActions";
import {
  SelectCell,
  SelectHeader,
} from "components/shared/table/SelectCheckbox";

const columnHelper = createColumnHelper();

export const columns = [
  columnHelper.display({
    id: "select",
    header: SelectHeader,
    cell: SelectCell,
  }),

  // PHP: Id
  columnHelper.accessor("id", {
    id: "id",
    header: "Id",
    cell: (info) => info.getValue(),
  }),

  // PHP: P.O Number
  columnHelper.accessor("po_number", {
    id: "po_number",
    header: "P.O Number",
    cell: (info) => info.getValue(),
    filterFn: (row, columnId, filterValue) => {
      if (filterValue === "3") return true; // All
      const status = row.original.status; // Assuming there's a status field
      if (filterValue === "1") return status === "approved";
      if (filterValue === "2") return status === "unapproved";
      return true;
    },
  }),

  // PHP: Generated By
  columnHelper.accessor("generated_by", {
    id: "generated_by",
    header: "Generated By",
    cell: (info) => info.getValue(),
  }),

  // PHP: Vendor Name
  columnHelper.accessor("vendor_name", {
    id: "vendor_name",
    header: "Vendor Name",
    cell: (info) => info.getValue(),
  }),

  // PHP: Prepared by
  columnHelper.accessor("prepared_by", {
    id: "prepared_by",
    header: "Prepared by",
    cell: (info) => info.getValue(),
  }),

  // PHP: Approved by
  columnHelper.accessor("approved_by", {
    id: "approved_by",
    header: "Approved by",
    cell: (info) => info.getValue(),
  }),

  // PHP: Added On
  columnHelper.accessor("added_on", {
    id: "added_on",
    header: "Added On",
    cell: (info) => {
      const date = info.getValue();
      if (!date) return "";
      const formattedDate = new Date(date).toLocaleDateString("en-GB");
      return formattedDate;
    },
  }),

  // PHP: Action
  columnHelper.display({
    id: "actions",
    header: () => (
      <div className="flex items-center justify-center">Action</div>
    ),
    cell: RowActions,
  }),
];
