// Import Dependencies
import { useParams, useNavigate } from "react-router-dom";
import { useState, useEffect, useMemo } from "react";
import { Button, Card, Spinner } from "components/ui";
import { Page } from "components/shared/Page";
import axios from "utils/axios";
import { toast } from "sonner";
import { ArrowLeftIcon, PrinterIcon, PaperClipIcon } from "@heroicons/react/24/outline";
import dayjs from "dayjs";

// ----------------------------------------------------------------------

export default function ViewVerification() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  const permissions = useMemo(() => {
    const raw = localStorage.getItem("userPermissions") || "[]";
    try {
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed.map(Number) : [];
    } catch {
      return raw.trim().replace(/^\[/, "").replace(/\]$/, "").split(",").map(Number).filter((n) => !isNaN(n));
    }
  }, []);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const response = await axios.get(`/quality-documents/get-lims-existing-detail?id=${id}`);
        if (response.data) {
          setData(response.data);
        } else {
          toast.error("Verification details not found ❌");
        }
      } catch (err) {
        console.error("Error fetching verification details:", err);
        toast.error("Failed to fetch details ❌");
      } finally {
        setLoading(false);
      }
    };

    if (permissions.includes(473)) {
      fetchData();
    }
  }, [id, permissions]);

  const handlePrint = () => {
    window.print();
  };

  if (!permissions.includes(473)) {
    return (
      <Page title="Verification – Access Denied">
        <div className="flex h-60 items-center justify-center rounded-xl border border-red-200 bg-red-50 dark:border-red-800 dark:bg-red-900/20">
          <p className="text-sm font-medium text-red-600 dark:text-red-400">
            ⛔ Access Denied — Permission 473 required
          </p>
        </div>
      </Page>
    );
  }

  if (loading) {
    return (
      <Page title="Verification Details">
        <div className="flex h-60 items-center justify-center">
          <Spinner size="lg" />
        </div>
      </Page>
    );
  }

  if (!data) {
    return (
      <Page title="Verification Details">
        <div className="text-center py-20">
          <p className="text-gray-500">Details not available.</p>
          <Button 
            className="mt-4"
            onClick={() => navigate("/dashboards/quality-documents/verification-lims")}
          >
            Back to List
          </Button>
        </div>
      </Page>
    );
  }

  const isRejected = data.status === -1;
  const isApproved = data.status === 2;

  return (
    <Page title="Verification Details">
      <div className="px-(--margin-x) py-6 max-w-5xl mx-auto">
        {/* Actions Bar (No Print) */}
        <div className="flex items-center justify-between mb-6 no-print">
          <Button
            variant="flat"
            onClick={() => navigate("/dashboards/quality-documents/verification-lims")}
            prefix={<ArrowLeftIcon className="size-4" />}
          >
            Back to List
          </Button>
          <Button
            color="primary"
            onClick={handlePrint}
            prefix={<PrinterIcon className="size-4" />}
          >
            Print Form
          </Button>
        </div>

        <Card className="p-8 bg-white dark:bg-dark-900 border-gray-300 dark:border-dark-400 shadow-lg print:shadow-none print:border-none print:p-0">
          {/* Header Section */}
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-gray-400">
              <tbody>
                <tr>
                  <td rowSpan={6} className="border border-gray-400 p-4 w-1/5 text-center align-top">
                    <img 
                      src="/images/letterhead.jpg" 
                      alt="Logo" 
                      className="mx-auto mb-2 w-36 object-contain"
                      onError={(e) => { e.target.src = "https://via.placeholder.com/150x50?text=Logo"; }}
                    />
                    <div className="text-[10px] font-bold uppercase text-gray-700 dark:text-dark-200">
                      KAILTECH TEST AND RESEARCH CENTRE
                    </div>
                  </td>
                  <th rowSpan={6} className="border border-gray-400 p-4 w-1/2 text-center text-lg font-bold uppercase bg-gray-50 dark:bg-dark-800">
                    VERIFICATION OF THE DOCUMENT GENERATED BY LIMS VS EXISTING FORMAT
                  </th>
                  <th className="border border-gray-400 p-2 text-left text-xs font-semibold w-[15%]">QF. No.</th>
                  <td className="border border-gray-400 p-2 text-xs">KTRC/QF/0804/01</td>
                </tr>
                <tr>
                  <th className="border border-gray-400 p-2 text-left text-xs font-semibold">Issue No.</th>
                  <td className="border border-gray-400 p-2 text-xs">01</td>
                </tr>
                <tr>
                  <th className="border border-gray-400 p-2 text-left text-xs font-semibold">Issue Date</th>
                  <td className="border border-gray-400 p-2 text-xs">10.03.2023</td>
                </tr>
                <tr>
                  <th className="border border-gray-400 p-2 text-left text-xs font-semibold">Revision No.</th>
                  <td className="border border-gray-400 p-2 text-xs">-</td>
                </tr>
                <tr>
                  <th className="border border-gray-400 p-2 text-left text-xs font-semibold">Revision Date</th>
                  <td className="border border-gray-400 p-2 text-xs">-</td>
                </tr>
                <tr>
                  <th className="border border-gray-400 p-2 text-left text-xs font-semibold">Page</th>
                  <td className="border border-gray-400 p-2 text-xs">1 of 1</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="mt-8 space-y-6">
            {/* Activity and Date */}
            <table className="w-full border-collapse border border-gray-400">
              <thead>
                <tr className="bg-gray-50 dark:bg-dark-800">
                  <th className="border border-gray-400 p-3 text-center w-4/5 font-bold uppercase tracking-wider">Activity Name</th>
                  <th className="border border-gray-400 p-3 text-center w-1/5 font-bold uppercase tracking-wider">Date</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-gray-400 p-4 min-h-[100px] align-top">{data.activity || "—"}</td>
                  <td className="border border-gray-400 p-4 text-center font-medium">
                    {data.date ? dayjs(data.date).format("DD/MM/YYYY") : "—"}
                  </td>
                </tr>
              </tbody>
            </table>

            {/* Verification Points Table */}
            <table className="w-full border-collapse border border-gray-400 mt-6">
              <thead>
                <tr className="bg-gray-50 dark:bg-dark-800 text-xs">
                  <th className="border border-gray-400 p-3 text-center w-16">S.No.</th>
                  <th className="border border-gray-400 p-3 text-left">Verification Points</th>
                  <th className="border border-gray-400 p-3 text-left">Remarks</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-400">
                {(data.verification_items || []).map((item, index) => (
                  <tr key={index}>
                    <td className="border border-gray-400 p-3 text-center font-medium">{index + 1}.</td>
                    <td className="border border-gray-400 p-3">{item.verfication}</td>
                    <td className="border border-gray-400 p-3">{item.remark || "—"}</td>
                  </tr>
                ))}
                {(data.verification_items || []).length === 0 && (
                  <tr>
                    <td colSpan={3} className="border border-gray-400 p-8 text-center text-gray-500 italic">
                      No verification points available.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>

            {/* Attachment */}
            {data.attachment_url && (
              <div className="mt-6 no-print">
                <Button
                  as="a"
                  href={data.attachment_url}
                  target="_blank"
                  variant="flat"
                  color="primary"
                  prefix={<PaperClipIcon className="size-4" />}
                >
                  View Attachment
                </Button>
              </div>
            )}

            {/* Signature Section */}
            <div className="mt-12 grid grid-cols-2 gap-8 border-t border-gray-200 dark:border-dark-600 pt-8">
              <div className="space-y-2">
                <h4 className="text-sm font-bold uppercase text-gray-500">Prepared & Verified By:</h4>
                <div className="text-lg font-semibold text-gray-800 dark:text-dark-50">
                  {data.creator_name || "—"}
                </div>
              </div>

              <div className="space-y-4">
                <h4 className="text-sm font-bold uppercase text-gray-500">Approved By:</h4>
                {isApproved ? (
                  <div className="space-y-3">
                    <div className="text-lg font-semibold text-gray-800 dark:text-dark-50">
                      {data.approver_name || "—"}
                    </div>
                    {data.digital_signature && (
                      <div className="bg-gray-50 dark:bg-dark-800 p-2 rounded-lg border border-gray-100 dark:border-dark-700 inline-block">
                        <img 
                          src={data.digital_signature} 
                          alt="Digital Signature" 
                          className="max-h-24 object-contain mix-blend-multiply dark:mix-blend-normal"
                        />
                      </div>
                    )}
                    {data.approved_on && (
                      <div className="text-xs text-gray-500 font-medium italic">
                        Date: {dayjs(data.approved_on).format("DD/MM/YYYY")}
                      </div>
                    )}
                  </div>
                ) : isRejected ? (
                  <div className="text-xl font-black text-red-600 uppercase tracking-tighter italic">
                    Rejected !!
                  </div>
                ) : (
                  <div className="text-sm text-gray-400 italic">Pending Approval</div>
                )}
              </div>
            </div>
          </div>
        </Card>

        {/* Global Print Styles */}
        <style>
          {`
            @media print {
              .no-print {
                display: none !important;
              }
              body {
                background: white !important;
                padding: 0 !important;
                margin: 0 !important;
              }
              .Page-root {
                padding: 0 !important;
                margin: 0 !important;
              }
              table {
                border-color: #000 !important;
              }
              th, td {
                border-color: #000 !important;
                color: #000 !important;
              }
            }
          `}
        </style>
      </div>
    </Page>
  );
}
