export const electricalSafetyList = [
  {
    id: 1,
    description: "Insulation (Optional) 500V",
    specification: ">-2 MΩ",
    safetyType: "Electrical Safety Test",
    tolerance: "Yes",
  },
  {
    id: 2,
    description: "Patient Lead Leakage Current, Isolation Test (mains on Applied part) (CF)",
    specification: "<-10 µA",
    safetyType: "Electrical Safety Test",
    tolerance: "Yes",
  },
  {
    id: 3,
    description: "Patient Lead Leakage Current, Isolation Test (mains on Applied part) (BF)",
    specification: "<-100 µA",
    safetyType: "Electrical Safety Test",
    tolerance: "Yes",
  },
  {
    id: 4,
    description: "Patient Leakage Current (CF)",
    specification: "<-10 µA",
    safetyType: "Electrical Safety Test",
    tolerance: "Yes",
  },
  {
    id: 5,
    description: "Earth Leakage Current (SFC)",
    specification: "<-1000 µA",
    safetyType: "Electrical Safety Test",
    tolerance: "Yes",
  },
  {
    id: 6,
    description: "Earth Leakage Current (NC)",
    specification: "<-500 µA",
    safetyType: "Electrical Safety Test",
    tolerance: "Yes",
  },
  {
    id: 7,
    description: "Equipment input current",
    specification: "0.1-10 A",
    safetyType: "Basic Safety & Performance Test",
    tolerance: "No",
  },
  {
    id: 8,
    description: "Voltage Neutral to Earth",
    specification: "<-1 V",
    safetyType: "Basic Safety & Performance Test",
    tolerance: "No",
  },
  {
    id: 9,
    description: "Voltage Line to Neutral",
    specification: "225.4-234.6 V",
    safetyType: "Basic Safety & Performance Test",
    tolerance: "No",
  },
  {
    id: 10,
    description: "Voltage Line to Earth",
    specification: "225.4-234.6 V",
    safetyType: "Basic Safety & Performance Test",
    tolerance: "No",
  },
];
